apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: hono-api
build:
  artifacts:
    - image: hono-api
      docker:
        dockerfile: ./app/Dockerfile
      context: ../app
  local:
    push: false
    useBuildkit: true
  tagPolicy:
    gitCommit:
      variant: AbbrevCommitSha
deploy:
  helm:
    releases:
      - name: hono-api
        chartPath: ./app/helm
        setValues:
          name: hono-api
          replicas: 1
          image: hono-api
          qiitaUrl: https://qiita.com
          zennUrl: https://zenn.dev
profiles:
  - name: prd
    patches:
      - op: replace
        path: /deploy/helm/releases/0/setValues/replicas
        value: 2
  - name: with-mock
    activation:
      - command: dev
    patches:
      - op: add
        path: /build/artifacts/-
        value:
          image: wiremock-server
          docker:
            dockerfile: ./wiremock/docker/Dockerfile
            context: ./wiremock/docker
      - op: add
        path: /deploy/helm/releases/-
        value:
          name: qiita-api
          chartPath: ./wiremock/helm
          setValues:
            name: qiita-api
            port: 3000
            image: wiremock-server
      - op: add
        path: /deploy/helm/releases/-
        value:
          name: zenn-api
          chartPath: ./wiremock/helm
          setValues:
            name: zenn-api
            port: 3001
            image: wiremock-server
  - name: remove-app
    activation:
      - command: dev
    patches:
      - op: remove
        path: /build/artifacts/0
      - op: remove
        path: /deploy/helm/releases/0
